### PR TITLE
Few fixes for xchain-terra

### LINKED ISSUE #481: [xchain-terra] Export `DECIMAL_TERRA`
Similar to other `xchain-*` packages

### LINKED ISSUE #482: [xchain-util] Rename `LUNAChain` -> `TerraChain`
## Currently 

```ts
export const LUNAChain = Chain.Terra
```
^ https://github.com/xchainjs/xchainjs-lib/blob/0325f4f3de3123e778b28c06730ff36b5440b0d7/packages/xchain-util/src/chain.ts#L22

## WANT
```ts
export const TerraChain = Chain.Terra
```

### LINKED ISSUE #483: [xchain-terra] Fix chain in constructor
Currently `Chain.Litecoin` instead of  `Chain.Terra` is passed

https://github.com/xchainjs/xchainjs-lib/blob/0325f4f3de3123e778b28c06730ff36b5440b0d7/packages/xchain-terra/src/client.ts#L95

### PR DESCRIPTION
**Pull request by veado**
- [x] Rename `LUNAChain`-> `TerraChain` 
- [x] Fix `chain` in constructor
- [x] ADD `TERRA_DECIMAL`, `isTerraNativeAsset`
- [x] Test `util`
- [x] `getTerraMicroDenom` returns null for invalid denominations
- [x] Bump `xchain-terra@0.1.0-alpha.2` + `xchain-util@0.5.2`

Fix #483
Close #481
Close #482

### CODE REVIEW

File: packages/xchain-terra/src/client.ts [hunk 1]
```diff
@@ -179,12 +178,14 @@ class Client extends BaseXChainClient implements XChainClient {
 
   async transfer({ walletIndex = 0, asset = AssetLUNA, amount, recipient, memo }: TxParams): Promise<string> {
     if (!this.validateAddress(recipient)) throw new Error(`${recipient} is not a valid terra address`)
-    if (!isTerraAsset(asset)) throw new Error(`${assetToString(asset)} is not a valid terra chain`)
 
     const mnemonicKey = new MnemonicKey({ mnemonic: this.phrase, index: walletIndex })
     const wallet = this.lcdClient.wallet(mnemonicKey)
 
     const terraMicroDenom = getTerraMicroDenom(asset.symbol as TerraNativeAsset)
+
```
Comment (mikewyszinski) [inline packages/xchain-terra/src/client.ts:186]: small issue, we should do any params checks before making the  (expensive) create wallet

**Review by mikewyszinski — COMMENTED** [review]
added 1 bit of feedback

File: packages/xchain-terra/src/client.ts (hunk 1 above)
Comment (veado) [reply packages/xchain-terra/src/client.ts:186]: Sorry, I've missed you feedback! Let's fix it in `alpha.3`

Comment (veado) [reply packages/xchain-terra/src/client.ts:186]: Fix https://github.com/xchainjs/xchainjs-lib/pull/486
