### PR TITLE
Fix/556 gas calc

### LINKED ISSUE #556: [xchain-thorchain] Another try to use `gas: auto` + `gasAdjustment: 1.5` (or higher)
to fix `out of gas`. Discusssion https://discord.com/channels/838986635756044328/967336653075132448/967365186774257664

### PR DESCRIPTION
**Pull request by mikewyszinski**
Close #556

### CODE REVIEW

File: packages/xchain-thorchain/src/util.ts [hunk 1]
```diff
@@ -235,7 +236,31 @@ export const buildUnsignedTx = ({
...
   return new cosmosclient.TxBuilder(cosmosSdk, txBody, authInfo)
 }
+export const getGasExpectedForTx = async ({
+  cosmosSDKClient,
+  txBody,
+  privKey,
+}: {
+  cosmosSDKClient: CosmosSDKClient
+  txBody: proto.cosmos.tx.v1beta1.TxBody
+  privKey: proto.cosmos.crypto.secp256k1.PrivKey
```
Comment (veado) [inline packages/xchain-thorchain/src/util.ts:246]: Remove `privKey` and pass `account: proto.cosmos.auth.v1beta1.IBaseAccount` instead. Or `sequence` and `account_number` instead of `account`. This will save request of `cosmosSDKClient.getAccount`, which might been already done by a caller of `getGasExpectedForTx`  (see `client.transfer`)

File: packages/xchain-thorchain/src/client.ts [hunk 2]
```diff
@@ -613,6 +631,32 @@ class Client extends BaseXChainClient implements ThorchainClient, XChainClient {
...
+      if (gas_expected === undefined) {
+        throw new Error('could not estimate gas limit required for TX')
+      }
+      const gasLimit = cosmosclient.Long.fromString(gas_expected).multiply(multiplier).toString()
+
+      return gasLimit
+    } catch (error) {
+      console.error(error)
+      console.warn(`Using the fallbackGasLimit of ${fallbackGasLimit} `)
+      return fallbackGasLimit
```
Comment (veado) [inline packages/xchain-thorchain/src/client.ts:657]: Don't return a hard-coded fallback. If `getGasExpectedForTx` fails there is a reason and broadcasting a tx won't work after that. Because `getGasExpectedForTx` includes a call of `buildUnsignedTx` which should not fail.

File: packages/xchain-thorchain/src/client.ts [hunk 3]
```diff
@@ -613,6 +631,32 @@ class Client extends BaseXChainClient implements ThorchainClient, XChainClient {
       return getDefaultFees()
     }
   }
+
+  private async determineGasLmit({
```
Comment (veado) [inline packages/xchain-thorchain/src/client.ts:635]: Pls rename `determineGasLmit` to `estimateGasLimit` or even better: Remove this function (see next comment below)

File: packages/xchain-thorchain/src/client.ts [hunk 4]
```diff
@@ -613,6 +631,32 @@ class Client extends BaseXChainClient implements ThorchainClient, XChainClient {
...
+    privKey: proto.cosmos.crypto.secp256k1.PrivKey
+    multiplier: number
+    fallbackGasLimit: string
+  }): Promise<string> {
+    try {
+      const gas_expected = await getGasExpectedForTx({ cosmosSDKClient: this.getCosmosClient(), txBody, privKey })
+      if (gas_expected === undefined) {
+        throw new Error('could not estimate gas limit required for TX')
+      }
+      const gasLimit = cosmosclient.Long.fromString(gas_expected).multiply(multiplier).toString()
```
Comment (veado) [inline packages/xchain-thorchain/src/client.ts:651]: ^ This could be already done in `util.getGasExpectedForTx`. And by removing the fallback (see another comment below), determineGasLmit can be removed from client.

**Review by veado — CHANGES_REQUESTED** [review]
LGTM - just some suggestions ...

Remove `package-lock.json`

File: packages/xchain-thorchain/src/util.ts [hunk 5]
```diff
@@ -235,7 +236,31 @@ export const buildUnsignedTx = ({
...
+}): Promise<string | undefined> => {
+  const accAddress = cosmosclient.AccAddress.fromPublicKey(privKey.pubKey())
+  const account = await cosmosSDKClient.getAccount(accAddress)
+  const txBuilder = buildUnsignedTx({
+    cosmosSdk: cosmosSDKClient.sdk,
+    txBody: txBody,
+    gasLimit: DEFAULT_GAS_LIMIT_VALUE, // NOTE: this should not matter since we are just doign an estimate
```
[the remark this answers is not in the document]
Comment (mikewyszinski) [reply packages/xchain-thorchain/src/util.ts:253]: yep, good idea. done

File: packages/xchain-thorchain/src/util.ts [hunk 6]
```diff
@@ -235,7 +236,31 @@ export const buildUnsignedTx = ({
 
   return new cosmosclient.TxBuilder(cosmosSdk, txBody, authInfo)
 }
+export const getGasExpectedForTx = async ({
```
[the remark this answers is not in the document]
Comment (mikewyszinski) [reply packages/xchain-thorchain/src/util.ts:239]: done

File: packages/xchain-thorchain/src/util.ts [hunk 7]
```diff
@@ -20,8 +20,9 @@ import { MsgNativeTx } from './types/messages'
 import types from './types/proto/MsgCompiled'
 
 export const DECIMAL = 8
-export const DEFAULT_GAS_VALUE = '4000000'
-export const DEPOSIT_GAS_VALUE = '500000000'
+export const DEFAULT_GAS_ESTIMATE_MULTIPLIER = 2
```
[the remark this answers is not in the document]
Comment (mikewyszinski) [reply packages/xchain-thorchain/src/util.ts:23]: done

File: packages/xchain-thorchain/src/util.ts (hunk 1 above)
Comment (mikewyszinski) [reply packages/xchain-thorchain/src/util.ts:246]: 1. i recall trying to invoke the /simulate endpoint with an unsigned tx and getting some kind of error.
2. the problem is that transferOffline() also calls determineGasLimit() and it doesn't have an account, so i just knowingly made another possibly redundant call to getAccount() inside getGasExpectedForTx() to keep it simple.

we can discuss this one further if you think it's better to try to get rid of it.

File: packages/xchain-thorchain/src/client.ts (hunk 2 above)
Comment (mikewyszinski) [reply packages/xchain-thorchain/src/client.ts:657]: hmm interesting...i was thinking if there is some kind of issue with calling /simulate, the tx should at least give it a try   it another try with the back up gas limit? I'll let you respond before removing the  fallback entirely

File: packages/xchain-thorchain/src/client.ts (hunk 4 above)
Comment (mikewyszinski) [reply packages/xchain-thorchain/src/client.ts:651]: agreed, if I remove fallback gas limits, this entire method can be removed...so i'll wait until you reply above ;-)

File: packages/xchain-thorchain/src/client.ts (hunk 3 above)
Comment (mikewyszinski) [reply packages/xchain-thorchain/src/client.ts:635]: done

**Review by veado — DISMISSED** [review]

**Review by Thorian1te — APPROVED** [review]
lgtm
