### PR TITLE
Github Workflow for test + precommit linting + fix linting issues

### LINKED ISSUE #23: Setup Github Actions to run tests for all packages
- Remove deprecated `.gitlab-ci.yml` in each package

### PR DESCRIPTION
**Pull request by HelloKashif**
Closes #23 #25

### CODE REVIEW

**Review by stuartkuentzel — APPROVED** [review]

File: packages/xchain-bitcoin/src/client.ts [hunk 1]
```diff
@@ -311,9 +311,9 @@ class Client implements BitcoinClient, XChainClient {
     }
     const calcdFees: Fees = {
       type: feesOptions.type,
-      fast: baseAmount(feesOptions.fast!.amount().multipliedBy(nextBlockFeeRate)),
-      average: baseAmount(feesOptions.average!.amount().multipliedBy(nextBlockFeeRate)),
-      fastest: baseAmount(feesOptions.fastest!.amount().multipliedBy(nextBlockFeeRate)),
+      fast: baseAmount(feesOptions.fast?.amount().multipliedBy(nextBlockFeeRate)),
+      average: baseAmount(feesOptions.average?.amount().multipliedBy(nextBlockFeeRate)),
+      fastest: baseAmount(feesOptions.fastest?.amount().multipliedBy(nextBlockFeeRate)),
```
Comment (veado) [inline packages/xchain-bitcoin/src/client.ts:316]: @HelloKashif ^ It will break if `feesOptions.fast` or `feesOptions.average` or `feesOptions.fastest` is undefined.

**Comment by veado** [comment]
@HelloKashif Pls check GH actions again:

Screenshot from 2020-10-30 06-51-15

^ https://github.com/xchainjs/xchainjs-lib/actions

File: packages/xchain-bitcoin/src/client.ts (hunk 1 above)
Comment (HelloKashif) [reply packages/xchain-bitcoin/src/client.ts:316]: @veado feesOptions is defined above so it shouldn't be undefined.
We can either move to ! mark instead of ?
OR
put a default value using ?? like
`feesOption.fast?.amount() ?? 5`

which one do you recommend?

Comment (veado) [reply packages/xchain-bitcoin/src/client.ts:316]: I would recommend to change `type Fees` as follow to avoid optional values.
```
type Fees = {
    type: FeeType
    fastest: BaseAmount
    fast: BaseAmount
    average: BaseAmount
};
```
If there is any chain, which provides one fee only, we will set same value for `average`, `fast`, `fastest`. It will be easier for frontends, too.
